apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-build
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: nodejs-build
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=git://github.com/zeruk/test-slo-nodejs.git#refs/heads/main"
          - "--context-sub-path=/nodejs"
          - "--dockerfile=Dockerfile"
          - "--destination=cr.yandex/crpho4srfnemeb9mi57a/nodejs:latest"
          - "--insecure"
        volumeMounts:
          - name: kaniko-docker-vol
            mountPath: /kaniko/.docker
      volumes:
        - name: kaniko-docker-vol
          secret:
            secretName: kaniko-docker
            items:
            - key: kanikoSecret.json
              path: config.json