apiVersion: ydb.tech/v1alpha1
kind: Database
metadata:
  name: database-sample
spec:
  additionalLabels:
    ydb-cluster: slo-storage
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: ydb-cluster
                operator: In
                values:
                  - slo-storage
          topologyKey: "kubernetes.io/hostname"
  image:
    name: cr.yandex/crptqonuodf51kdj7a7d/ydb:22.2.22
  nodes: 6
  resources:
    containerResources:
      limits:
        cpu: 100m
    storageUnits:
      - count: 1
        unitKind: ssd
  storageClusterRef:
    name: storage-sample