name: Errors shedule action

inputs:
  time_between_phases:
    description: 'Time to wait between phases (sleep command)'
    default: '1m'
    type: string
  KUBE_CONFIG:
    required: true

runs:
  using: "composite"
  steps:
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}
    
    - name: Get DB host's internal IP
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ inputs.KUBE_CONFIG }}
      with:
        args: get pods database-sample-0 -o=jsonpath='{.status.podIP}'
        redirect-to: MARTYR_IP

    - name: Show DB host's internal IP
      shell: bash
      run: echo ${MARTYR_IP}

    - name: Freeze tablet
      uses: actions-hub/kubectl@master
      with:
        args: >
          run -it --image=busybox --rm tablet-freezer --restart=Never -- sh -c "wget -q -O-
          '${MARTYR_IP}:8765/tablets/app?TabletID=72057594037968897&node=1&page=SetFreeze&freeze=1'"
    
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}

    - name: Unfreeze tablet
      uses: actions-hub/kubectl@master
      with:
        args: >
          run -it --image=busybox --rm tablet-freezer --restart=Never -- sh -c "wget -q -O-
          '${MARTYR_IP}:8765/tablets/app?TabletID=72057594037968897&node=1&page=SetFreeze&freeze=0'"
    
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}

    - name: Delete database pod (it will automatically restart)
      uses: actions-hub/kubectl@master
      with:
        args: delete pod database-sample-1
    
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}

    - name: Hard shutdown database pod (it will automatically restart)
      uses: actions-hub/kubectl@master
      with:
        args: delete pod database-sample-1 --force=true --now=true
    
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}

    - name: Kill pod from inside
      uses: actions-hub/kubectl@master
      with:
        args: exec -it database-sample-0 -- /bin/bash -c "kill -2 1 && echo 'process killed'";
    
    - name: Wait ${{ inputs.time_between_phases }}
      shell: bash
      run: sleep ${{ inputs.time_between_phases }}
