name: Build SDK workload flow

on:
  workflow_call:
    inputs:
      language:
        description: 'SDK language or language+variant'
        default: 'nodejs'
        required: true
        type: string
      build_timeout:
        description: 'Timeout to build image'
        default: '5m'
        required: false
        type: string
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  build-workload-image:
    name: build-${{ inputs.language }}
    runs-on: ubuntu-latest
    steps:
      - name: Create ${{ inputs.language }} image build yaml
        run: |
          cat > ${{ inputs.language }}-build.yaml <<EOF
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: ${{ inputs.language }}-build
          spec:
            ttlSecondsAfterFinished: 120
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                - name: ${{ inputs.language }}-build
                  image: gcr.io/kaniko-project/executor:latest
                  args:
                    - "--context=git://github.com/zeruk/test-slo-nodejs.git#refs/heads/main"
                    - "--context-sub-path=/${{ inputs.language }}"
                    - "--dockerfile=Dockerfile"
                    - "--destination=cr.yandex/crpho4srfnemeb9mi57a/${{ inputs.language }}:latest"
                    - "--insecure"
                  volumeMounts:
                    - name: kaniko-docker-vol
                      mountPath: /kaniko/.docker
                volumes:
                  - name: kaniko-docker-vol
                    secret:
                      secretName: kaniko-docker
                      items:
                      - key: kanikoSecret.json
                        path: config.json
          EOF

      - name: Check builded yaml
        run: cat ${{ inputs.language }}-build.yaml

      # TODO: Uncommenct when will be debugged enough

      # - name: Run ${{ inputs.language }} SDK test image build
      #   run: kubectl apply -f ${{ inputs.language }}-build.yaml

      # - name: Wait for the test image to build
      #   run: kubectl wait --for=condition=complete --timeout ${{ inputs.build_timeout }} job/${{ inputs.language }}-build

      # - name: Get build logs
      #   run: kubectl logs job/${{ inputs.language }}-build