name: Node.js CI

on:
  pull_request:
    branches: [ '**', '!slo' ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:latest
        ports:
          - 2135:2135
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'

    env:
      YDB_SHUTDOWN_URL: http://localhost:8765/actors/kqp_proxy?force_shutdown=all

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build library
      run: npm run build
    - name: Build examples
      run: npm link && cd examples && npm i && npm link ydb-sdk && npm run build
    - name: Run tests
      run: npm run test:all
      env:
        YDB_SSL_ROOT_CERTIFICATES_FILE: /tmp/ydb_certs/ca.pem
