name: Create YDB cluster in k8s workflow

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: mkdir $HOME/.kube; echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Get existing pods
        run: kubectl get pods

      - name: Create storage nodes
        run: kubectl apply -f slo/k8s/storage.yaml
      
      - name: Wait until storage nodes become ready
        run: kubectl wait --for=jsonpath="{.status.state}"="Ready" storages.ydb.tech storage-sample

      - name: Create database nodes
        run: kubectl apply -f slo/k8s/database.yaml
      
      - name: Wait until database nodes become ready
        run: kubectl wait --for=jsonpath="{.status.state}"="Ready" database.ydb.tech database-sample