name: Create YDB cluster in k8s workflow

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get existing pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Create storage nodes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f slo/k8s/storage.yaml
      
      - name: Wait until storage nodes become ready
        uses: actions-hub/kubectl@master
        with:
          args: wait --for=jsonpath='{.status.state}'="Ready" storages.ydb.tech storage-sample

      - name: Create database nodes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f slo/k8s/database.yaml
      
      - name: Wait until database nodes become ready
        uses: actions-hub/kubectl@master
        with:
          args: wait --for=jsonpath='{.status.state}'="Ready" database.ydb.tech database-sample