name: Delete YDB cluster in k8s workflow

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get existing pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

      - name: Delete storage nodes
        uses: actions-hub/kubectl@master
        with:
          args: delete -f slo/k8s/storage.yaml

      - name: Delete database nodes
        uses: actions-hub/kubectl@master
        with:
          args: delete -f slo/k8s/database.yaml
      
      - name: Delete persistent volume claims
        uses: actions-hub/kubectl@master
        with:
          args: delete pvc `kubectl get pvc -o=jsonpath="{.items[*].metadata.name}"`
