name: Delete YDB cluster in k8s workflow

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  delete-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: mkdir $HOME/.kube; echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Get existing pods
        run: kubectl get pods

      - name: Delete storage nodes
        run: kubectl delete -f slo/k8s/storage.yaml

      - name: Delete database nodes
        run: kubectl delete -f slo/k8s/database.yaml
      
      - name: Delete persistent volume claims
        run: kubectl delete pvc `kubectl get pvc -o=jsonpath="{.items[*].metadata.name}"`
