name: Full SLO test workflow

on:
  pull_request:
    branches: [ 'slo' ]

jobs:
  create-cluster:
    uses: ./.github/workflows/create-cluster.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  delete-cluster:
    uses: ./.github/workflows/create-cluster.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
