name: Full SLO test workflow

on:
  pull_request:
    branches: [ 'slo' ]

jobs:

  create-cluster:
    uses: ./.github/workflows/create-cluster.yml
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  build-nodejs:
    uses: ./.github/workflows/build-workload.yml
    secrets: 
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    with:
      language: nodejs

  run-nodejs:
    needs: [create-cluster, build-nodejs]
    uses: ./.github/workflows/run-slo.yml
    secrets: inherit
    with:
      language: nodejs

  # TODO: Uncomment when will be debugged enough
  # delete-cluster:
  #   needs: [test-flow]
  #   uses: ./.github/workflows/delete-cluster.yml
  #   secrets:
  #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
