name: All SDKs test flow


on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true

jobs:
  nodejs:
    uses: ./.github/workflows/test-flow-template.yml
    secrets: inherit
    with:
      language: nodejs
  nodejs-v2:
    uses: ./.github/workflows/test-flow-template.yml
    secrets: inherit
    with:
      language: nodejs-v2
